workflows:
  android-debug-workflow:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Set up local.properties
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Set gradlew permissions
        script: | 
          chmod +x gradlew
      - name: Build debug APK
        script: | 
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - mugaliamar@gmail.com
        notify:
          success: true
          failure: true
